<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>VisionWeave.App</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" />
    <PackageReference Include="Nodify" />
    <PackageReference Include="WPF-UI" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VisionWeave.Application\VisionWeave.Application.csproj" />
    <ProjectReference Include="..\VisionWeave.OpenCv\VisionWeave.OpenCv.csproj" />
    <ProjectReference Include="..\VisionWeave.Persistence\VisionWeave.Persistence.csproj" />
    <ProjectReference Include="..\VisionWeave.PluginSdk\VisionWeave.PluginSdk.csproj" />
  </ItemGroup>

</Project>
