<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>VisionWeave.OpenCv</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" />
    <PackageReference Include="OpenCvSharp4.runtime.win" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VisionWeave.Contracts\VisionWeave.Contracts.csproj" />
  </ItemGroup>

</Project>
