<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>VisionWeave.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VisionWeave.Contracts\VisionWeave.Contracts.csproj" />
    <ProjectReference Include="..\VisionWeave.Domain\VisionWeave.Domain.csproj" />
  </ItemGroup>

</Project>
